<!----------------------------------------------------
-- Plantilla HTML para la pagina de administraccion --
----------------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="home">
    <div class="container">
        <h1>Tus RSS</h1>
    </div>
</main>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>