<!----------------------------------------------------
-- Plantilla HTML para la pagina de administraccion --
----------------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<h1>Administracion</h1>


<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>