<!---------------------------------
-- Plantilla HTML para el footer --
---------------------------------->
<footer class="footer">
    <div class="container row">
        <div>
            <span>Todos los derechos reservados NEWS ATTACK @ Copyrigth</span>
        </div>
    </div>
</footer>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://static.sekandocdn.net/static/feednami/feednami-client-v1.1.js"></script>
<script type="text/javascript" src="/public/js/main.js"></script>
</body>
</html>