<!-----------------------------------
-- Plantilla HTML para la cabecera --
------------------------------------>
<header class="header">
    <div class="container column">
        <div class="row between bottom">
            <div class="logo">
                <a href="/">
                    <img src="./public/images/logo.png">
                </a>
            </div>
            <div class="menu row">
                <div class="menu__search-box">
                    <input type="text">
                </div>
                <div class="menu__register">
                    <a class="button red" href="./auth">Registrarse</a>
                </div>
                <div class="menu__login">
                    <a class="button red" href="./auth">Login</a>
                </div>
            </div>
        </div>
        <div class="separator"></div>
    </div>
</header>