<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="home">
    <div class="container">
        <h1>Que es News Attcack?</h1>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <h1>Tutorial</h1>
        <div class="tutorial row between">
            <div class="card column">
                <h6>1</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>2</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>3</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>3</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>1</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>2</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>3</h6>
                <img src="./public/images/proto.png">
            </div>
            
        </div>
        <h1>Desarrolladores</h1>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

    </div>
</main>
s

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>