<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="home">
    <div class="container">
        <h1>Que es News Attack?</h1>
        <p>News Attack es un sitio web donde podrás agrupar todas las noticias que sean de tu interés
          de forma fácil y sencilla. Siguiendo el tutorial a continuación, aprenderás a buscar tus canales
          de noticias favoritos y guardarlos como favoritos para tenerlos siempre al alcance de tu mano.</p>
        <h1>Tutorial</h1>
        <div class="tutorial row between">
            <div class="card column">
                <h6>1</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>2</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>3</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>3</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>1</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>2</h6>
                <img src="./public/images/proto.png">
            </div>
            <div class="card column">
                <h6>3</h6>
                <img src="./public/images/proto.png">
            </div>

        </div>
        <h1>Desarrolladores</h1>
        <p>News Attack ha sido desarrollado por <b>Josue Martín Sánchez</b>, <b>Sergio García García</b>,
          <b>David Ballester Velez</b> y <b>Pau Marqués</b>, estudiantes de DAW a través de UOC y Jesuïtes
        educació.</p>

    </div>
</main>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>
