<!-------------------------------------------
-- Plantilla HTML para la pagina principal --
-------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="dashboard">
    <div class="container">
        <h1>Noticias</h1>
        <div class="filters">
            <ul class="tags row">
                <?php 
                    $array = array('Pais', 'Internacional', 'Economia', 'Moda', 'Otras');
                    foreach ($array as &$valor) {
                ?>
                <li id="articles-tag"><?php echo $valor ?></li>
                <?php } ?>
            </ul>
        </div>

        <div id="articles-area" class="content row between">
        </div>
        <div class="error-modal"></div>
    </div>
</main>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>