<!-------------------------------------------
-- Plantilla HTML para la pagina principal --
-------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="dashboard">
    <div class="container">
        <h1>Noticias</h1>
        <div class="filters">
            <ul class="tags row">
            <?php 
                $array = array('Pais', 'Internacional', 'Economia', 'Moda', 'Otras');
                foreach ($array as &$valor) {
            ?>
                <li onClick="console.log('click')"><?php echo $valor ?></li>
            <?php
                }
            ?>
            </ul>
        </div>

        <div class="content row between">
        <?php 
            $array = array(1, 2, 3, 4, 5, 6);
            foreach ($array as &$valor) {
        ?>
            <div class="card">
                <div class="card__img">
                    <img src="./public/images/world.png">
                </div>
                <div class="card__content">
                    <div class="row between">
                        <div class="header-icon">
                            <img src="./public/images/accenture.jpg" />
                        </div>
                        <div class="header-title">
                            <h3>El cohete de Space X</h3>
                            <h6>La Compañia Space X tiene nuevo cohete</h6>
                        </div>
                        <div class="header-time">
                            <span>15m</span>
                        </div>
                    </div>
                    <div>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
                    </div>
                    <div class="row between">
                        <span class="button red outline" onClick="">Eliminar</span>
                        <span class="button yellow outline" onClick="">Ver más!</span>
                    </div>
                </div>
            </div>
        <?php
            }
        ?>
        </div>
    </div>
</main>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>