
<!------------------------------------------
-- Plantilla HTML para la pagina de perfil --
------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="home">
    <div class="container">
        <h1>Perfil</h1>
        <h6>Nombre y Apellidos</h6>
        <input type="text" value="Antonio Fernandez"/>
        <h6>Correo electronico</h6>
        <input type="text" value="antonio.ferz.135@gmail.com"/>
        <h6>Otros datos</h6>
        <input type="text" value="Pues un poco de todo"/>
    </div>
</main>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>