<!---------------------------------------------------
-- Plantilla HTML para la pagina de registro/login --
---------------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="auth">
    <div class="container">
        <h1>Registro | Login</h1>

        <div class="box">
            <form>
                <input class="white" type="text" placeholder="Nombre de usuario"/>
                <input class="white" type="text" placeholder="Email"/>
                <input class="white" type="text" placeholder="Contraseña"/>
                <div class="row end">
                    <a class="button yellow" href="./dashboard">Registrarse</a>
                </div>
            </form>
        </div>
    </div>
</main>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>