<!---------------------------------------------------
-- Plantilla HTML para la pagina de registro/login --
---------------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<h1>Registro | Login</h1>


<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>